name: 'Delete CloudFormation Stacks'
author: 'shiftcode GmbH'
description: 'Delete multiple cloudformation stacks by prefix and stage suffix'
inputs:
  stackNamePrefix:
    description: 'prefix of the stack names to delete'
    required: true
  waitForDeleteComplete:
    description: 'whether or not the action should run (wait) until the stack is completely deleted'
    required: true
    default: 'false'
  ignoreBranches:
    description: 'provide a list of branches to ignore (JSON array)'
    required: true
    default: '[]'
runs:
  using: 'node20'
  main: 'dist/index.js'
